# Generated by Django 4.2.7 on 2023-12-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("dep", models.CharField(max_length=50)),
            ],
        ),
    ]
